<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'E-mail' => 'E-mail',
    'Username' => 'İstifadəçi adı',
    'Authorization' => 'Daxil ol',
    'Captcha' => 'Captcha',
    'Check your E-mail for further instructions' => 'Sonraki əməliyyatlar üçün e-mailınızı yoxlayın',
    'Check your e-mail {email} for instructions to activate account' => 'Akkauntunuzu aktivləşdirmək üçün {email} e-mailınızı yoxlayın',
    'Confirm' => 'təsdiqləmək',
    'Confirm E-mail' => 'E-mailı təsdiqləmək',
    'Continue' => 'Davam etmək',
    'Could not send confirmation email' => 'Akkauntu aktivləşdirmək üçün məktubu göndərmək mümkün deyil',
    'E-mail confirmation for' => 'E-mail təsdiqlənməsi',
    'E-mail confirmed' => 'E-mail təsdiqləndi',
    'E-mail is invalid' => 'E-mail yanlışdır',
    'Forgot password ?' => 'Şifrənizi unutduz?',
    'Incorrect username or password.' => 'E-mail və ya şifrə yanlışdır',
    'Login' => 'İstifadəçi adı',
    'Login has been taken' => 'İstifadəçi adı artıq məşğuldur',
    'Password' => 'Şifrə',
    'Password recovery' => 'Şifrənin bərpa edilməsi',
    'Password reset for' => 'Смена пароля для',
    'Recover' => 'Bərpa etmək',
    'Register' => 'Qeydiyyatdan keçmək',
    'Registration' => 'Qeydiyyat',
    'Registration - confirm your e-mail' => 'Qeydiyyat - e-mailınızı təsdiq edin',
    'Remember me' => 'Məni yadda saxla',
    'Repeat password' => 'Şifrəni təkrarla',
    'This E-mail already exists' => 'Bu E-mail artıq məşğuldur',
    'Token not found. It may be expired' => 'Təhlükəsizlik kodu tapılmadı yə yaxud yenilənməsini tələb edir',
    'Token not found. It may be expired. Try reset password once more' => 'Təhlükəsizlik kodu tapılmadı yə yaxud yenilənməsini tələb edir. Şifrəni bərpa etmək üçün bir də cəhd edin.',
    'Too many attempts' => 'Həddindən artıq cəhd etmisiniz',
    'Unable to send message for email provided' => 'Qeyd olunmuş e-maila məktub göndərmək mümkün deyil',
    'You could not login from this IP' => 'Siz bu IP-dən daxil ola bilmərsiniz',

    'Hello {fullname}, follow this link to reset your password' =>
    'Hörmətli {fullname}, şifrəni yeniləmək üçün bu linkə keçin'
];
